//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\projects\FluentTranslate\src\FluentTranslate.FtlParser\Fluent.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FluentParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IFluentVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.fluent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFluent([NotNull] FluentParser.FluentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage([NotNull] FluentParser.MessageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.messageContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageContent([NotNull] FluentParser.MessageContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] FluentParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.comment3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment3([NotNull] FluentParser.Comment3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.comment2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment2([NotNull] FluentParser.Comment2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.comment1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment1([NotNull] FluentParser.Comment1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.commentLine3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentLine3([NotNull] FluentParser.CommentLine3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.commentLine2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentLine2([NotNull] FluentParser.CommentLine2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FluentParser.commentLine1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentLine1([NotNull] FluentParser.CommentLine1Context context);
}
