global using Antlr4.Runtime;
global using FluentAssertions;
global using FluentTranslate.Common;
global using FluentTranslate.Domain;
global using FluentTranslate.Options;
global using FluentTranslate.Parser;
global using FluentTranslate.Services;
global using FluentTranslate.Tests.Support;
global using NUnit.Framework;
global using System.Collections;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Reflection;
global using System.Text.Json;
global using static FluentTranslate.Tests.Support.Helpers;
