//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\projects\FluentTranslate\src\FluentTranslate.Parser\FluentParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFluentParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class FluentParserBaseListener : IFluentParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource([NotNull] FluentParser.ResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource([NotNull] FluentParser.ResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.entry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntry([NotNull] FluentParser.EntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.entry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntry([NotNull] FluentParser.EntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] FluentParser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] FluentParser.MessageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.emptyLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyLine([NotNull] FluentParser.EmptyLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.emptyLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyLine([NotNull] FluentParser.EmptyLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] FluentParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] FluentParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] FluentParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] FluentParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.textBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextBlock([NotNull] FluentParser.TextBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.textBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextBlock([NotNull] FluentParser.TextBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.textInline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextInline([NotNull] FluentParser.TextInlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.textInline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextInline([NotNull] FluentParser.TextInlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] FluentParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] FluentParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.placeable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlaceable([NotNull] FluentParser.PlaceableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.placeable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlaceable([NotNull] FluentParser.PlaceableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.placeableExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlaceableExpression([NotNull] FluentParser.PlaceableExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.placeableExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlaceableExpression([NotNull] FluentParser.PlaceableExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.inlineExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineExpression([NotNull] FluentParser.InlineExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.inlineExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineExpression([NotNull] FluentParser.InlineExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] FluentParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] FluentParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberLiteral([NotNull] FluentParser.NumberLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberLiteral([NotNull] FluentParser.NumberLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluentParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableReference([NotNull] FluentParser.VariableReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluentParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableReference([NotNull] FluentParser.VariableReferenceContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
